version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    restart: always

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
